name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-version: ['1.25']
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Run tests with coverage
      run: |
        WD=$(pwd)
        cd testdata/zaplogger/zapwrappers && go get ./... && cd ${WD}
        cd testdata/zaplogger/zapusages && go get ./... && cd ${WD}
        go test -v -race -coverprofile=coverage.out ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-version: ['1.25']
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.4.0
